name: ci-test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.8
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: mod download
        run: go mod tidy

      - name: Test
        run: go test -v .